image: docker:latest
services:
  - docker:dind

stages:
  - test
  - deploy

step-develop:
  stage: test
  only:
    - develop
  tags:
    - develop
  script:
    - echo running tests in develop

step-uat:
  stage: deploy
  only:
    - uat
  tags:
    - uat
  script:
    - echo setting up env uat
    - sudo apt-get install -y python-pip
    - sudo pip install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d

step-deploy-staging:
  stage: deploy
  only:
    - staging
  tags:
    - staging
  script:
    - echo setting up env staging
    - sudo apt-get install -y python-pip
    - sudo pip install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d

step-deploy-production:
  stage: deploy
  only:
    - production
  tags:
    - production
  script:
    - echo setting up env production
    - sudo apt-get install -y python-pip
    - sudo pip install docker-compose
    - sudo docker image prune -f
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d
  when: manual



